language: python

sudo: false
branches:
  only:
    - master

python:
  - "2.7"

install:
 - python setup.py install
 - pip install epydoc

script:
  - epydoc --html --name="GlobalPayments.Api" -v -o docs globalpayments

deploy:
  local-dir: docs
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
